0|Cyberpunk-Edge|~/.config/swww/Cyberpunk-Edge/lucy_2.png
0|Catppuccin-Latte|~/.config/swww/Catppuccin-Latte/jormungandr.jpg
0|Decay-Green|~/.config/swww/Decay-Green/moments_before_desk.png
0|Rose-Pine|~/.config/swww/Rose-Pine/mountain_dragon_pink.jpg
0|Tokyo-Night|~/.config/swww/Tokyo-Night/lowpoly_street.png
0|Material-Sakura|~/.config/swww/Material-Sakura/material_pastel_4.jpg
0|Graphite-Mono|~/.config/swww/Graphite-Mono/gojo.png
0|Cyberpunk-Edge|~/.config/swww/Cyberpunk-Edge/lucy_1.jpg
0|Frosted-Glass|~/.config/swww/Frosted-Glass/teal_mountain.png
