#!/usr/bin/bash

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

# notification daemon
dunst &

# battery notification
$scripts/default/battery_notif &

# screen locking when idle
$scripts/default/idle_handler &

# effects
# $scripts/rgb &

# other
## persistent clipboard
wl-clip-persist --clipboard regular &
wl-paste --watch cliphist store &

# ... this might not be necessary anymore ? idk
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &

# launch portals after executing the above
# $scripts/default/launch_portals &
