#!/bin/sh
HISTSIZE=2000
SAVEHIST=2000
export_os
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export GRADLE_HOME=$HOME/.local/share/gradle/latest
export SXHKD_SHELL="/usr/bin/sh"
export EDITOR="nvim"
export TERMINAL="foot"
export TERM=xterm
export NNN_PLUG='f:finder;o:fzopen;p:mocq;d:diffs;t:nmount;v:imgview'

if [[ -d "/opt/homebrew" ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$HOME/.local/bin":$PATH
export PATH=${GRADLE_HOME}/bin:$PATH
export PATH="$PATH:$(go env GOBIN):$(go env GOPATH)/bin"
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
export PATH="$PATH:$HOME/.local/bin"

# source /etc/zsh_command_not_found
