[config]
reload_gtk_theme = false

[templates.alacritty-colors]
input_path = "~/.config/matugen/templates/alacritty-colors.toml"
output_path = "~/.config/alacritty/colors.toml"


[templates.starship]
input_path = "~/.config/matugen/templates/starship.toml"
output_path = "~/.config/starship.toml"

[templates.niri-layout]
input_path = "~/.config/matugen/templates/niri-layout.kdl"
output_path = "~/.config/niri/cfg/layout.kdl"
